### ISSUE TITLE
kann Modpack nicht fertig downloaden

### ISSUE THREAD

**Issue by lug2003** [AtomSponge/hosencorp-1#76]
Als ich versucht habe das Modpack zu downloaden kommt immer,wenn er bei Minecraft -Assets ist das:

Error beim downloden einer Datei für das folgende Pack:Hosencorp
Faild to download http://resources.download.minecraft.net/ad/ad7d770b7fff3b64121f75bd60cecfc4866d1cd6
Bitte sprich mit dem Macher des Packs.

Dies ist auch bei jedenm anderen Pack bei Technik Launcher und FTB:
Außerdem ist es bei meinen beiden Computern. 

Bitte kann mir jeman helfen.

**Comment by Luggagga** [comment]
Um das ganze nochmal zu beleben, der Beitrag ist ja schon etwas älter, ich hab das gleiche Problem und kenne leider keine Antwort... wäre sehr dankbar für Hilfe

**Comment by Bandelenth** [comment]
Wir bieten grundsätzlich keinen Support mehr für das Hosencorp-Modpack der ersten Generation an, weil wir selbst keine Testumgebung mehr dafür haben. Ich kann dazu nur sagen, dass bei mir die Datei sich problemlos im Browser laden lässt und auch auf Servern von Mojang liegt, daher haben wir damit eigentlich nichts zu tun, ich habe keine Ahnung warum die Fehlermeldung auf den Modpackersteller hinweist. Bitte überprüft doch mal, ob ihr die Datei auch im Browser herunterladen könnt, dann ist sie erreichbar und sollte auch vom Launcher geladen werden, falls nicht, müsstet ihr mal das Internet nach ähnlichen Fehlermeldungen durchsuchen, diese ist meiner Auffassung nach generisch und damit sowieso grundsätzlich außerhalb unserer Reichweite. Ich hoffe das hilft erstmal so weiter... Bei konkreten Fragen zu Ergebnissen daraus, stehe ich grundsätzlich zur Verfügung, aber bitte nur, wenn es wirklich sein muss, da wie oben angesprochen, eigentlich kein Support mehr besteht.

**Comment by AtomSponge** [comment]
Wie bereits auf @Luggagga's Tweet geantwortet, hier nochmal in abgeänderter Form:

Da der Fehler hier beim Download einer Datei von http://resources.download.minecraft.net auftritt, liegt dieser, wie @Bandelenth bereits erwähnte, außerhalb unserer Reichweite und wir können diesen nicht beheben. Falls das Problem erneut auftritt, einige Minuten warten und erneut versuchen, da der Server hinter der betroffenen Adresse wahrscheinlich zeitweise nicht erreichbar war.

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
