### ISSUE TITLE
modpack startet nicht bzw. block ids überlagern sich

### ISSUE THREAD

**Issue by Newsandbuy** [AtomSponge/hosencorp-1#80]
Hallo

das modpack startet nicht das heißt es bleibt bei mojang stehen und wenn es startet dann steht dort nur das sich die mekanism ids sich überlagern 
consolenLog:

http://pastebin.com/8dhSE9Fq
//Anmerkung: Ich habe das mal zugunsten der Übersichtlichkeit auf eine eigene Seite verschoben ^Ba

weiter geht es nicht ich habe jetzt 2 stunden gewartet

**Comment by Bandelenth** [comment]
In den Logs ist nichts von einem ID-Conflict zu finden. Ich kann das Problem leider auch nicht reproduzieren.

**Comment by Newsandbuy** [comment]
ist ok kannst closen windows 10 hat mit dem letzten update sehr viel kaputt gemacht mit dem neuen geht es wieder
